version: '3.9'

services: 
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file: ./backend/.env
        environment:      
          - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
          - "3306:3306"
        volumes:
          - db:/var/lib/mysql
        networks:
          - backend
    backend:
      depends_on:
         - mysqldb
      build: 
          context: ./backend
          dockerfile: Dockerfile

      container_name: backend
      restart: unless-stopped
      env_file: ./backend/.env
      ports:
        - "4000:4000"
      environment:
        - DB_HOST=mysqldb
        - DB_USER=$MYSQLDB_USER
        - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - DB_NAME=$MYSQLDB_DATABASE
        - DB_PORT=$MYSQLDB_DOCKER_PORT
        - CLIENT_ORIGIN=$CLIENT_ORIGIN
      networks:
        - backend
        - frontend
    frontend:
      depends_on:
        - backend
      build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
      container_name: frontend
      ports:
        - "3000:3000"
      networks:
        - frontend  

volumes: 
  db:

networks:
  backend:
  frontend:
